#
#  Source:
#


apiVersion: v1
kind: ServiceAccount
metadata:
  name: $$service-name
  namespace: $$service-namespace
  labels:
    app: $$service-name
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $$service-name
  labels:
    app: $$service-name
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch



---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $$service-name
roleRef:
  kind: ClusterRole
  name: $$service-name
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: $$service-name
  namespace: $$service-namespace



---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: $$service-name
  namespace: $$service-namespace
  labels:
    app: $$service-name
spec:
  selector:
    matchLabels:
      app: $$service-name
  template:
    metadata:
      labels:
        app: $$service-name
    spec:
      serviceAccount: $$service-name
      serviceAccountName: $$service-name
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: $$service-name-container
#        image: fluent/fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch
        image: $$service-image
        
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
#            value: "elastic-search.$$service-namespace"
            value: "elastic-search.$$service-namespace.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
#          - name: FLUENT_UID
#            value: "0"
#          - name: FLUENT_ELASTICSEARCH_USER
#            value: none
#          - name: FLUENT_ELASTICSEARCH_PASSWORD
#            value: none
        
        resources: 
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - mountPath: /var/log/journal
          name: journal
      
      terminationGracePeriodSeconds: 30
      
      volumes: 
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: journal
        hostPath: 
          path: /run/log/journal
        


















