apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $$service-name-cluster
  namespace: $$service-namespace
spec:
  serviceName: $$service-name
  replicas: 3
  selector:
    matchLabels:
      app: $$service-name
  template:
    metadata:
      labels:
        app: $$service-name
    spec:
      containers:
      - name: $$service-name-container
      
        image: $$service-image
#        image: elasticsearch/elasticsearch-oss:6.6.1
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: elasticsearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "$$service-name-cluster-0.$$service-name,$$service-name-cluster-1.$$service-name,$$service-name-cluster-1.$$service-name"
          - name: cluster.initial_master_nodes
            value: "$$service-name-cluster-0,$$service-name-cluster-1,$$service-name-cluster-2"
          # - name: discovery.zen.ping.unicast.hosts
          #   value: "$$service-name-cluster-0.$$service-name,$$service-name-cluster-1.$$service-name,$$service-name-cluster-2.$$service-name"
          # - name: discovery.zen.minimum_master_nodes
          #   value: "2"
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g -XX:+UseG1GC -XX:MaxGCPauseMillis=400"
      initContainers:
      - name: fix-permissions
        image: library/busybox:1.32.0
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: library/busybox:1.32.0
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: library/busybox:1.32.0
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      # Volumes
  volumeClaimTemplates:
  - metadata:
      name: esdata
      namespace: $$service-namespace
      labels:
        app: $$service-name
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ""
      resources:
        requests:
          storage: 3Gi

---
kind: Service
apiVersion: v1
metadata:
  name: $$service-name
  namespace: $$service-namespace
  labels:
    app: $$service-name
spec:
  selector:
    app: $$service-name
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: rest
  - protocol: TCP
    port: 9300
    targetPort: 9300
    name: inter-node
    
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: $$service-namespace
  name: curator-cron
  labels:
    app: curator
spec:
  schedule: "$$clean-schedule"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          #
          #  Must sync to elastic search version
          #
          - image: bobrik/curator:5.8.1
            name: curator-container
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
            - name: config
              mountPath: /etc/config
          volumes:
          - name: config
            configMap:
              name: curator-config
          restartPolicy: OnFailure


