#
# refer to https://github.com/kubernetes/kubeadm/issues/1152
# and https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#sig-cluster-lifecycle

apiVersion: kubeadm.k8s.io/v1alpha3

kind: ClusterConfiguration

networking:
  podSubnet: 192.168.0.0/16

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1

kind: KubeProxyConfiguration

clusterCIDR: 192.168.0.0/16

---
apiVersion: kubeadm.k8s.io/v1alpha3

kind: InitConfiguration

bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
  
api:
  advertiseAddress: 10.1.165.22

---

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

failSwapOn: false

#
# centos1.lab.sensus.net:/root> kubeadm config view
#

apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta1
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: ""
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.14.4
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}

